name: DelayTest
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup git client
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          
      - name: Test CherryPick
        uses: MintPlayer/github-actions/cherry-pick@main
        with:
          milliseconds: 1000
        continue-on-error: true
        
      - name: Test Delay
        uses: MintPlayer/github-actions/delay@main
        with:
          milliseconds: 1000
        continue-on-error: true
      
      #- name: CodeQL
      #  uses: github/codeql-action/init@v2
