name: DelayTest
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: MintPlayer/github-actions/cherry-pick@v1
        with:
          milliseconds: 1000
      
      #- name: CodeQL
      #  uses: github/codeql-action/init@v2
