name: DelayTest
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #- name: Setup git client
      #  run: |
      #    git config user.email "action@github.com"
      #    git config user.name "GitHub Action"
          
      - name: Test CherryPick
        uses: MintPlayer/github-actions/cherry-pick@v1.0.7
        with:
          milliseconds: 1000
        continue-on-error: true
        
      - name: Test Delay
        uses: MintPlayer/github-actions/delay@main
        with:
          milliseconds: 1000
        continue-on-error: true
      
      #- name: CodeQL
      #  uses: github/codeql-action/init@v2
