name: DelayTest
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delay
        uses: MintPlayer/github-actions/delay@v1
        with:
          milliseconds: '1000'
      #- name: CodeQL
      #  uses: github/codeql-action/init@v2
